name: Update Readme Actions
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

# 이 부분 추가
permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Badges - README
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: "username.87afed76"
